name: Release JAR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # 允许上传 Release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: chmod +x gradlew
      - run: ./gradlew build shadowJar   # 生成 fat jar

      # 自动发布 Release（tag 为当前日期-时间）
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.TOKEN }}
          automatic_release_tag: latest
          title: Latest Build
          files: |
            build/libs/*.jar
